name: linters

on:
  pull_request:
    paths:
      - "functions/**.js"
      - "functions/.eslintrc.json"
      - "functions/package-lock.json"

jobs:
  eslint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Functions node_modules cache
        uses: actions/cache@v2
        id: functions-node-modules-cache
        with:
          key: functions-node-modules-cache-${{ hashFiles('functions/package-lock.json') }}
          path: 'functions/node_modules'

      - name: Install functions dependencies
        if: steps.functions-node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci --prefix functions

      - name: Run ESLint
        run: npm run lint --prefix functions
