name: production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Functions node_modules cache
        uses: actions/cache@v2
        id: functions-node-modules-cache
        with:
          key: functions-node-modules-cache-${{ hashFiles('functions/package-lock.json') }}
          path: 'functions/node_modules'

      - name: Install functions dependencies
        if: steps.functions-node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci --prefix functions

      - name: Deploy
        run: firebase deploy --project ${{ secrets.FIREBASE_PRODUCTION_APPLICATION_NAME }}
